defmodule Scrawly.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rooms) do
      modify :code, :text, null: true
    end
  end

  def down do
    alter table(:rooms) do
      modify :code, :text, null: false
    end
  end
end
