defmodule Scrawly.Repo.Migrations.AddCreatorIdToRooms do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute """
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'words' AND column_name = 'difficulty'
      ) THEN
        ALTER TABLE words ADD COLUMN difficulty text NOT NULL DEFAULT 'medium';
      END IF;
    END $$;
    """

    alter table(:rooms) do
      add :creator_id,
          references(:users,
            column: :id,
            name: "rooms_creator_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:rooms, "rooms_creator_id_fkey")

    alter table(:rooms) do
      remove :creator_id
    end

    alter table(:words) do
      remove :difficulty
    end
  end
end
