defmodule Scrawly.Repo.Migrations.AddUserAccentColor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :accent_color, :text, null: false, default: "green"
    end
  end

  def down do
    alter table(:users) do
      remove :accent_color
    end
  end
end
