defmodule Scrawly.Repo.Migrations.WordDifficulty do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:words) do
      add :difficulty, :text, null: false, default: "medium"
    end
  end

  def down do
    alter table(:words) do
      remove :difficulty
    end
  end
end
