defmodule Scrawly.Repo.Migrations.AddRoundDetailsToGames do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:games) do
      add :round_details, {:array, :map}, default: []
    end
  end

  def down do
    alter table(:games) do
      remove :round_details
    end
  end
end
