defmodule Scrawly.Repo.Migrations.AddWordCountAndRoomSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:words) do
      add :word_count, :bigint, null: false, default: 1
    end

    alter table(:rooms) do
      add :word_count, :bigint, null: false, default: 1
      add :word_source, :text, null: false, default: "local"
      add :prompt, :text
    end
  end

  def down do
    alter table(:rooms) do
      remove :prompt
      remove :word_source
      remove :word_count
    end

    alter table(:words) do
      remove :word_count
    end
  end
end
