defmodule Scrawly.Repo.Migrations.RenameAccentPaletteToFrameworks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :accent_color, :text, default: "purple"
    end

    # Remap the old freeform palette (green/blue/pink) onto the new framework
    # palette. `orange` is preserved across both palettes.
    execute(
      "UPDATE users SET accent_color = 'purple' WHERE accent_color IN ('green', 'blue', 'pink')"
    )
  end

  def down do
    alter table(:users) do
      modify :accent_color, :text, default: "green"
    end

    execute("UPDATE users SET accent_color = 'green' WHERE accent_color IN ('purple', 'yellow')")
  end
end
