defmodule Scrawly.Repo.Migrations.AddDeviceIdToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :email, :citext, null: true
      add :device_id, :uuid
    end

    create unique_index(:users, [:device_id], name: "users_unique_device_id_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:device_id], name: "users_unique_device_id_index")

    alter table(:users) do
      remove :device_id
      modify :email, :citext, null: false
    end
  end
end
