defmodule Scrawly.Repo.Migrations.AddRoundDurationToRooms do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rooms) do
      add :round_duration, :bigint, null: false, default: 60
    end
  end

  def down do
    alter table(:rooms) do
      remove :round_duration
    end
  end
end
