defmodule Scrawly.Repo.Migrations.AddAvatarToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :avatar_id, :text, null: false, default: "a-mushroom"
      add :avatar_color, :text, null: false, default: "3"
    end
  end

  def down do
    alter table(:users) do
      remove :avatar_color
      remove :avatar_id
    end
  end
end
