defmodule Scrawly.Repo.Migrations.AddRoundMultiplierAndAiTone do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rooms) do
      add :round_multiplier, :bigint, null: false, default: 1
      add :ai_tone, :text, null: false, default: "fun"
    end
  end

  def down do
    alter table(:rooms) do
      remove :ai_tone
      remove :round_multiplier
    end
  end
end
